### ISSUE TITLE
카카오로그인의 함수 일부가 deprecated 되었습니다.

### ISSUE THREAD

**Issue by gudi-escore** [WindSekirun/SocialLogin#13]
우선 좋은 예제 올려주셔서 감사합니다 ^^; 덕분에 요긴하게 잘 써먹고 있습니다.

requestOption의 프로퍼티 값도 변경되었고 MeResponseCallback 의 함수가 deprecated 되 있어서 V2 Method로 바꾸는걸 권장하던데 호출방법이 조금 다릅니다. 그래서 일단 제보 드립니다

**Comment by WindSekirun** [comment]
일단 저도 파악이 되야 하기 때문에, 조만간 업데이트를 진행하겠으나 시간이 좀 걸립니다. 그때까진 열어두도록 하겠습니다

제보 감사드립니다

**Comment by WindSekirun** [comment]
- [x] usermgmt 1.5.1 -> 1.11.1 로 마이그레이션
- [x] V2 methods 마이그레이션
- [x] 샘플 프로젝트 테스트
- [x] 프로덕션 테스트

적용 브랜치: 1.2.5-migrate-with-kakao-v2 (https://github.com/WindSekirun/SocialLogin/tree/1.2.5-migrate-with-kakao-v2)

**Comment by WindSekirun** [comment]
어느정도 구현은 완료되었습니다. 다만 실제 테스트가 필요하므로 SNAPSHOT 브랜치를 남깁니다.
implementation 'com.github.WindSekirun:SocialLogin:1.2.5-migrate-with-kakao-v2-SNAPSHOT'

**Comment by WindSekirun** [comment]
샘플 테스트가 완료되었습니다. 7.5일 후 정식 버전으로 릴리즈 하겠습니다.

**Comment by WindSekirun** [comment]
1.2.5 버전 릴리즈 하였습니다.
제보 감사드립니다!
